### ISSUE TITLE
Matching capital letters for rules

### ISSUE THREAD

**Issue by Neko-Box-Coder** [mkiol/dsnote#253]
First of all, thanks for sharing the project, really appreciate the effort that went into it.

There's regex support for rules but it seems like it seems like the capital letters matching will just match normal letters instead.
So if I want to match `PascalCase` and separate them into normal words like `pascal case`, I don't think it is possible to do that with the current regex in rules.

Is there any reason/limitations as to why a regex like ([A-Z]) won't match upper letters given there is an option to turn the matched word to lower cases with `\u\1`

Next, it is possible to freeze the rule text testing panel with misformed regex while testing the regex match. For example:

```
FORWARD test
PascalCase
```
Pattern: `([A-Z])`
Replacement text: `\u\1`

will freeze it immediately because it went into an infinite loop I guess. 

A minor inconvenience (compare to the ability of matching upper case) but will be a nice to have for having some sort of condition check for this sort of edge case.

Thanks

**Comment by mkiol** [comment]
Hello :)

> Is there any reason/limitations as to why a regex like ([A-Z]) won't match upper letters given there is an option to turn the matched word to lower cases with

No reason, it just wasn't implemented. Changed in 3108e41cc84a624912c5779761f57780390a7d8c. Support for "case sensitive" matching will be in the next version.

> Next, it is possible to freeze the rule text testing panel with misformed regex while testing the regex match.

Thank you for catching this! Fixed in 067682f18e965d12c030e157022c369532c146fe.

If you have any other needs or comments about the "Rules" feature, please let me know. A new version is coming, so this is the last moment to make changes.

**Comment by Neko-Box-Coder** [comment]
Thanks for the quick reply and fix, really appreciated. Nothing else in for the rules, it seems pretty powerful.

A few more mundane things, 
1. coqui has (very unfortunately) shutdown and the support of it had been ended judging from the repo activity. Just to let you know in case you missed it. It's really a shame since they have pretty great model + voices.
2. The link to WhisperSpeech is wrong in readme, I think they have moved to https://github.com/WhisperSpeech/WhisperSpeech
3. How easy/difficult it is to use/turn this to a C++ library? Just wondering

**Comment by mkiol** [comment]
> Nothing else in for the rules, it seems pretty powerful.

👍🏿 

> coqui has (very unfortunately) shutdown

It is very sad. Especially considering the speed, versatility and accuracy, the XTTS is, in my opinion, the best model for cloning. For the next Speech Note release, I've switched to [coqui-tts](https://pypi.org/project/coqui-tts/) "forked" package. It is still maintained (bug fixes), but nothing new has been added.

> The link to WhisperSpeech is wrong in readme

Thanks for letting me know. I will correct this.

> How easy/difficult it is to use/turn this to a C++ library?

Extremely difficult/not possible, sorry. Speech Note is a "frankenstain" app. It has so many dependencies that making it a standalone library would be a nightmare.
